### ISSUE TITLE
MRMS GageCorr Data only available before 15 Oct 2020 

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/data-retrieval-scripts#9]
@tombrauer @mikebartles @ejgumbel @joshuarwillis @FHanbali 

I have been looking for recent MRMS data and found the `GaugeCorr_QPE` grids seem are no longer served on the Iowa State Mesonet servers after 15 Oct 2020.  

When MRMS v 12.0 was released on 15 Oct 2020, they started to provide a new data product `MultiSensor_QPE_24H_Pass2` grids.  

>    https://inside.nssl.noaa.gov/mrms/past-code-updates/
>     In the MRMS v12.0 update to NCO section, the third bullet from the bottom:
>     -	Multi-sensor QPE scheme using gauges and model QPFs to fill radar coverage gaps
>     I think that suggests the MultiSensor_QPE is gage corrected.  So the data might have just changed names in the MRMS migration to 12.0.

I am looking for another set of eyes to confirm my assumption the `GageCorr_QPE` grids have just been renamed to `MultiSensor_QPE`.  I am working a study where we have calibration events pre/post MRMS v 12.0,  but I am a bit uneasy mixing the QPE grids.

Have any of you come across this before?

Thanks!

**Comment by FHanbali** [comment]
Hi Daniel, yes, we encountered this on Cumulus.  Your impressions are the same as ours.  GageCorr transition to latest MRMS products, with Pass2 incorporating more corrections than Pass1, but Pass2 lags Pass1 by a few hours in near realtime availability

**Comment by danhamill** [comment]
@FHanbali Thanks for your input. 

As of now, I have split the MRMS QPE download scripts into two scripts:
- pre MRMS v12.0

https://github.com/HydrologicEngineeringCenter/data-retrieval-scripts/blob/6a930e636325ecd84286a65e2282792de41c192a/MRMS_GageCorr_qpe_async_download.py#L36-L56

- post MRMS v12.0

https://github.com/HydrologicEngineeringCenter/data-retrieval-scripts/blob/6a930e636325ecd84286a65e2282792de41c192a/MRMS_multiSensor_qpe_async_download.py#L36-L70

These could easily be combined with some additional conditional logic when building the download urls.
